completed frontend structure: created directories with corresponding …
learn-academy-2023-golf/cat-tinder-frontend-mr-jv-cat-tinder pull request #1
Opened 2023-12-06 22:45 UTC by gencalada

…files, created app.js routes, added mockPigion array to app.js, and basic styling

2023-12-06 23:00 UTC, elysemontano requested changes
Left some comments on your Header and Footer.

2023-12-06 23:00 UTC, elysemontano commented on src/components/Footer.js
> +      <h1>Footer</h1>
I would suggest updating this with content that you actually want in the application like copyright and your names.

2023-12-06 23:00 UTC, elysemontano commented on src/components/Header.js
> +      </Nav>
I would also suggest updating this so that your navigation is usable and not just filler text.

2023-12-06 23:14 UTC, gencalada commented on src/components/Footer.js
> +      <h1>Footer</h1>
Okay, got it! getting right to it.

2023-12-06 23:15 UTC, gencalada commented on src/components/Header.js
> +      </Nav>
okay, thank you! We just overlooked the filler text 😅

2023-12-07 18:29 UTC, elysemontano approved these changes

2023-12-07 18:31 UTC, merged